/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CatchallRouteImport } from './routes/$catchall'

const CatchallRoute = CatchallRouteImport.update({
  id: '/$catchall',
  path: '/$catchall',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/$catchall': typeof CatchallRoute
}
export interface FileRoutesByTo {
  '/$catchall': typeof CatchallRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$catchall': typeof CatchallRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/$catchall'
  fileRoutesByTo: FileRoutesByTo
  to: '/$catchall'
  id: '__root__' | '/$catchall'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  CatchallRoute: typeof CatchallRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/$catchall': {
      id: '/$catchall'
      path: '/$catchall'
      fullPath: '/$catchall'
      preLoaderRoute: typeof CatchallRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  CatchallRoute: CatchallRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.ts'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
