#!/usr/bin/env bash
set -ex

__helper-enter-chroot() {
  sudo arch-chroot ./raspbian-chroot /bin/bash
}

__helper-prepare-chroot-host() {
  sudo pacman -S debootstrap arch-install-scripts
  sudo mkdir ./raspbian-chroot
  sudo debootstrap --arch=arm64 bookworm ./raspbian-chroot http://deb.debian.org/debian/
}

__helper-prepare-chroot-guest() {
  apt update
  apt install -y build-essential devscripts git curl gnupg

  curl -sSL "http://archive.raspberrypi.org/debian/raspberrypi.gpg.key" | gpg --dearmor -o /usr/share/keyrings/raspberrypi-archive-keyring.gpg
  echo "
deb [signed-by=/usr/share/keyrings/raspberrypi-archive-keyring.gpg] http://archive.raspberrypi.com/debian/ trixie main
deb-src [signed-by=/usr/share/keyrings/raspberrypi-archive-keyring.gpg] http://archive.raspberrypi.com/debian/ trixie main
" > /etc/apt/sources.list.d/raspi.list
  apt update

  mkdir -p ~/work/apt
  cd ~/work/apt
  chown -R _apt:root .

  export PATH=$PATH:/sbin:/usr/sbin
  apt source squeekboard
  cd squeekboard*/
  mk-build-deps -i ./debian/control
  DEB_BUILD_OPTIONS=nocheck dpkg-buildpackage -b -uc -us

  # TODO Disable mouse emulation on touch display
  # https://forums.raspberrypi.com/viewtopic.php?p=2293733#p2293733
  # Might be better in ~/.config/labwc/rc.xml
  # mouseEmulation="yes" -> mouseEmulation="no"

  # TODO install squeekboard mods
  # dpkg -i squeekboard.deb

  # TODO custom labwc autostart
  # - no panels
  # - `killall squeekboard || true; SQUEEKBOARD_LAYER=overlay squeekboard &`
}

__helper-prepare-device() {
  SSH_BASE=""
  SERVER_HOST=""
  FRAME_ID=""
  FRAME_ACCESS_KEY=""

  sudo mkdir -p /opt/gift-picture-frame
  sudo chown frame:frame /opt/gift-picture-frame

  cd /opt/gift-picture-frame

  scp "$SSH_BASE/build/gift-picture-frame-linux-arm64" .
  chmod +x gift-picture-frame-linux-arm64

  scp "$SSH_BASE/device-setup/raspberry-pi/squeekboard.deb" .
  sudo dpkg -i squeekboard.deb

  sudo apt install brightnessctl wlr-randr

  mkdir -p ~/.config/labwc
  cat <<EOF > ~/.config/labwc/autostart
ps aux | grep xwaylandvideobridge | awk '{ print \$2 }' | while read -r line; do kill "\$line"; done || true

ps aux | grep lwrespawn | awk '{ print \$2 }' | while read -r line; do kill "\$line"; done || true
killall pcmanfm || true
killall wf-panel-pi || true

cd /opt/gift-picture-frame
./gift-picture-frame-linux-arm64 frame start --server "$SERVER_HOST" --id "$FRAME_ID" --access-key "$FRAME_ACCESS_KEY" &
EOF

  sudo mkdir -p /usr/share/plymouth/themes/gift-picture-frame
  sudo scp -r "$SSH_BASE/device-setup/plymouth-theme/*" /usr/share/plymouth/themes/gift-picture-frame/
  sudo plymouth-set-default-theme -R gift-picture-frame
}
