publicHoistPattern:
  - eslint
  - prettier
  - vite
  - vitest
  - workbox-window
  - '@promoboxx/eslint-config'

packages:
  - ./internal/ui/frame-ui/
  - ./internal/ui/uploader-ui/
  - ./internal/ui/shared/
