#!/usr/bin/env bash
set -ex

if [ -z "$CI" ]; then
  ./script/prepare-env
fi

pushd ./internal/ui/frame-ui
  pnpm exec react-scripts build
popd

pushd ./internal/ui/uploader-ui
  pnpm exec react-scripts build
popd

ARCHS=(
  amd64
  # arm64
)
OSES=(
  linux
  # darwin
  # windows
)

for os in "${OSES[@]}"; do
  for arch in "${ARCHS[@]}"; do
    FILENAME="./build/$(basename "$PWD")-$os-$arch"
    GOOS="$os" GOARCH="$arch" go build -ldflags "-s -w" -o "$FILENAME" ./main.go
    chmod +x "$FILENAME"
  done
done

find ./build -name '*-windows-*' -not -name '*.exe' | while read -r line; do
  mv "$line" "$line.exe"
done
