#!/usr/bin/env bash
set -ex

DIRS=(
  "."
  "./internal/ui/shared"
  "./internal/ui/frame-ui"
  "./internal/ui/uploader-ui"
)

for dir in "${DIRS[@]}"; do
  pushd "$dir"
    rm -rf "./build"
    rm -rf "./dist"
    rm -rf "./tsc-output"
    rm -rf "./node_modules"
  popd
done
