#!/usr/bin/env bash
set -ex

EMBEDDED_PATHS=(
  ./internal/ui/frame-ui
  ./internal/ui/uploader-ui
)

for path in "${EMBEDDED_PATHS[@]}"; do
  mkdir -p "$path/build/client"
  touch "$path/build/client/index.html"
done

if [ ! -e frames.json ]; then
  ln -s ./frames.json-example ./frames.json
fi

pnpm install

pnpm exec tsc --build --emitDeclarationOnly
