#!/usr/bin/env bash
set -ex

pnpm install

pnpm exec tsc --build --emitDeclarationOnly

EMBEDDED_PATHS=(
  ./internal/ui/frame-ui
  ./internal/ui/uploader-ui
)

for path in "${EMBEDDED_PATHS[@]}"; do
  mkdir -p "$path/build/client"
  touch "$path/build/client/index.html"
done
