#!/usr/bin/env bash
set -ex

exec pnpm exec concurrently \
  "nodemon --watch ./ --ext go --signal SIGHUP --exec ./script/start-backends" \
  "cd ./internal/ui/client-ui && react-scripts-vite start" \
  "cd ./internal/ui/server-ui && react-scripts-vite start"
