#!/usr/bin/env bash
set -ex

if [ -z "$CI" ]; then
  ./script/prepare-env
  ./script/build
fi

PLATFORM_BIN="./build/gift-picture-frame-linux-amd64"

exec pnpm exec concurrently \
  "$PLATFORM_BIN uploader start" \
  "$PLATFORM_BIN frame start --id test --server http://localhost:8080"
